### ISSUE TITLE
Missing dependencies in fabric.mod.json

### ISSUE THREAD

**Issue by Poopooracoocoo** [DimasKama/SchematicPreview#2]
https://modrinth.com/mod/schematicpreview/version/0.0.7+1.21.4

https://github.com/DimasKama/SchematicPreview/blob/1.21.4/src/main/resources/fabric.mod.json#L24

You also need to replace the `fabric` dependency with `fabric-api`

The dependencies also missing on CurseForge https://www.curseforge.com/minecraft/mc-mods/schematicpreview/files/6226597/dependencies

**Comment by DimasKama** [comment]
Fixed in 0.0.8

https://modrinth.com/mod/schematicpreview/version/0.0.8+1.21.4

**Comment by Poopooracoocoo** [comment]
Dependencies are still missing on CurseForge. https://www.curseforge.com/minecraft/mc-mods/schematicpreview/files/6238728/dependencies

**Comment by DimasKama** [comment]
added them
