### ISSUE TITLE
game crashed using SchematicPreview

### ISSUE THREAD

**Issue by Nakik** [DimasKama/SchematicPreview#4]
Hey i have issue with the SchematicPreview Mod
on 1.21.4 the game crashing when opening the litematica Load Schematic

```js
java.lang.NoSuchMethodError: 'fi.dy.masa.malilib.util.position.Vec3i fi.dy.masa.litematica.schematic.LitematicaSchematic.getTotalSize()'
    at knot//ru.dimaskama.schematicpreview.gui.widget.SchematicPreviewWidget.renderPreviewAndOverlay(SchematicPreviewWidget.java:102)
    at knot//ru.dimaskama.schematicpreview.gui.widget.CustomDirectoryEntry.render(CustomDirectoryEntry.java:60)
    at knot//fi.dy.masa.malilib.gui.widgets.WidgetListBase.drawContents(WidgetListBase.java:425)
    at knot//fi.dy.masa.malilib.gui.widgets.WidgetFileBrowserBase.drawContents(WidgetFileBrowserBase.java:85)
    at knot//fi.dy.masa.malilib.gui.GuiListBase.drawContents(GuiListBase.java:178)
    at knot//fi.dy.masa.malilib.gui.GuiBase.method_25394(GuiBase.java:203)
    at knot//net.minecraft.class_437.method_47413(class_437.java:116)
    at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$118(class_757.java)
    at knot//net.minecraft.class_757.wrapOperation$dae000$fabric-screen-api-v1$onRenderScreen(class_757.java:1914)
    at knot//net.minecraft.class_757.method_3192(class_757.java:551)
    at knot//net.minecraft.class_310.method_1523(class_310.java:1341)
    at knot//net.minecraft.class_310.method_1514(class_310.java:922)
    at knot//net.minecraft.client.main.Main.main(Main.java:267)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by DimasKama** [comment]
Try to install the latest versions of malilib and litematica

**Comment by nyghtwulf** [comment]
Just got this same crash, using 0.0.8 of SchematicPreview with litematica 0.21.2 and maLiLib 0.23.2 just released a few hours ago. fabric 0.16.10 and fabric api0.118.0+1.21.4

**Comment by DimasKama** [comment]
Mod works good with these versions of litematica and malilib.

https://modrinth.com/mod/litematica/version/0.19.54
https://modrinth.com/mod/malilib/version/0.21.6

It is hard to follow all updates of these mods

**Comment by nyghtwulf** [comment]
> Mod works good with these versions of litematica and malilib.
> 
> https://modrinth.com/mod/litematica/version/0.19.54 https://modrinth.com/mod/malilib/version/0.21.6
> 
> It is hard to follow all updates of these mods

Those appear to be for minecraft 1.21.1. the version of SchematicPreview that I (and I presume OP) are using is https://modrinth.com/mod/schematicpreview/version/0.0.8+1.21.4 which is listed as being for 1.21.4.

**Comment by Nakik** [comment]
Ye, crashed happen when using schematicPreview for 1.21.4.
i can go down few versions of litematica/malilib but only if its for 1.21.4.
Tell me what version to use🙃

**Comment by DimasKama** [comment]
Fixed in new version
https://modrinth.com/mod/schematicpreview/versions

**Comment by Nakik** [comment]
game still crashing when using the mode.
the error i got(after less than 2min with mode)
```js


java.lang.ArrayIndexOutOfBoundsException: Index 538943 out of bounds for length 534668
	at knot//fi.dy.masa.litematica.schematic.container.LitematicaBitArray.getAt(LitematicaBitArray.java:70)
	at knot//fi.dy.masa.litematica.schematic.container.LitematicaBlockStateContainer.get(LitematicaBlockStateContainer.java:66)
	at knot//ru.dimaskama.schematicpreview.render.WorldSchematicWrapper.method_8320(WorldSchematicWrapper.java:267)
	at knot//ru.dimaskama.schematicpreview.render.SchematicPreviewRenderer.lambda$setup$0(SchematicPreviewRenderer.java:81)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)


A detailed walkthrough of the error, its code path and all known details is as follows:
--------------------------------------------------------------------------------------```
